# Path to images it can be ./ if the images are on the same directory of the executable or ./<directory name> if it is on
path: imageOfficeRotaTest
# The name of the image sequence without number sequence or extension
filename: reconstruct_image_
#Extension to saved images
extension: .jpg
# Positions file name
positions file name: rota_office_0.csv
# The name of the vision sensor at CoppeliaSim
# vision sensor names: [./Vision_sensor_center, ./Vision_sensor_left, ./Vision_sensor_right]
vision sensor names: [./Quadcopter/Vision_sensor]
# The name of the robot that is with the camera
quadcopter name: ./target
# The quadcopter handle to get quadcotper position
quadcopter base: ./base
